name: grpa
channels:
  - pytorch
  - nvidia
  - defaults
  - numba
dependencies:
  - python
  - numpy
  - nvidia::cudatoolkit>10.0
  - numba::llvmlite
  - pytorch
  - torchvision
  - matplotlib
  - pandas
  - pillow
  - tqdm
  - pyyaml
  - scikit-learn
  - seaborn