Training:
  iterations: 100
  debug: True
  learningrate: 0.001
  optimizer: ADAM
  weightdecay: 0.00
  batchsize: 16
  Saving:
    savehistory: True
    filename: debug2
    subfolder: dateTime # dateTime
    accuracyfreq: 10
  Randomseed: 100
  Model: './model_configs/LieModelPoint.yaml'
  Dataset: './dataset_configs/custom_circle.yaml'
